adventureworks:
  target: postgres
  outputs:
    postgres:  
      type: postgres
      host: localhost
      user: postgres
      password: Koala.2022
      port: 5432
      dbname: postgres
      schema: dbo
      threads: 12